#!/usr/bin/env python

import zmq
import os
import pipes

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect("tcp://dev01.trevorfitzgerald.com:5000")

socket.setsockopt(zmq.SUBSCRIBE, "message")

while True:
    name, message = socket.recv().split(" ", 1)
    os.system("terminal-notifier -title 'IRC' -subtitle %s -message %s" % (pipes.quote(name), pipes.quote(message)))
