#!/usr/bin/env python

import zmq
import os
import pipes

context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect("tcp://dev01.trevorfitzgerald.com:5000")

socket.setsockopt(zmq.SUBSCRIBE, "message")

while True:
    queue, data = socket.recv().split(" ", 1)
    name, message = data.split("\t", 1)

    # Mac OS X
    os.system("type terminal-notifier >/dev/null 2>&1 && terminal-notifier -title 'IRC' -group IRC -subtitle %s -message %s" % (pipes.quote(name), pipes.quote(message)))

    # Linux
    os.system("type notify-send >/dev/null 2>&1 && notify-send --icon=notification-message-im %s %s" % (pipes.quote(name), pipes.quote(message)))
