#!/usr/bin/env python

import zmq
import argparse
import os
import pipes
import sys

# get command line argument (hostname)
parser = argparse.ArgumentParser(description='Connect to notification queue')
parser.add_argument('hostname', nargs=1, help='The host you want to connect to')
args = parser.parse_args()
hostname = args.hostname[0]

# start socket connection
context = zmq.Context()
socket = context.socket(zmq.SUB)
try:
    socket.connect("tcp://%s:5000" % hostname)
except:
    print "Cannot make connection to %s." % hostname
    sys.exit(1)

# subscribe to `message` queue
socket.setsockopt(zmq.SUBSCRIBE, "message")

while True:
    try:
        queue, data = socket.recv().split(" ", 1)
        name, message = data.split("\t", 1)

        # Mac OS X
        os.system("type terminal-notifier >/dev/null 2>&1 && terminal-notifier -title 'IRC' -subtitle %s -message %s" % (pipes.quote(name), pipes.quote(message)))

        # Linux
        os.system("type notify-send >/dev/null 2>&1 && notify-send --icon=notification-message-im %s %s" % (pipes.quote(name), pipes.quote(message)))

    except (KeyboardInterrupt, SystemExit):
        sys.exit(' Quitting... ')
